//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace June_july_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemp
    {
        public int id { get; set; }
        public string name { get; set; }
    }
}
